_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
aug_mode:
    value: 2
batch_expansion_rate:
    value: 1.4
batch_expansion_th:
    value: 0.7
batch_size:
    value: 160
batch_size_limit:
    value: 256
dataset:
    value: mulran
dataset_folder:
    value: /code/SHeRLoc/src/dataset/HeRCULES
epochs:
    value: 120
loss:
    value: BatchHardTripletMarginLoss
lr:
    value: 0.0001
margin:
    value: 0.6
model_params.lidar_model:
    value: null
model_params.model_params_path:
    value: ../models/radarloc.txt
model_params.output_dim:
    value: 256
model_params.radar_model:
    value: radarloc
model_params_path:
    value: ../models/radarloc.txt
num_workers:
    value: 2
params_path:
    value: ../config/config_radarloc.txt
scheduler_milestones:
    value:
        - 80
test_file:
    value: /code/SHeRLoc/src/dataset/HeRCULES/test_R_Day_384.pickle
train_file:
    value: /code/SHeRLoc/src/dataset/HeRCULES/train_R/Library_Day_Library_Night_5_50_polar_nav.pickle
val_file:
    value: /code/SHeRLoc/src/dataset/HeRCULES/val_R/Library_Day_Library_Night_5_50_polar_nav.pickle
weight_decay:
    value: 0.001
