_wandb:
    value:
        cli_version: 0.22.2
        e:
            vnnzrar536tbi9itx39a3hh4ds7q8tms:
                args:
                    - --config
                    - ../config/config.txt
                    - --model_config
                    - ../models/Hetero_SHeRLoc.txt
                codePath: train.py
                codePathLocal: train.py
                email: hanjun815@snu.ac.kr
                executable: /usr/local/bin/python
                host: oem-System-Product-Name
                os: Linux-6.8.0-40-generic-x86_64-with-glibc2.31
                program: /code/SHeRLoc_pr/training/train.py
                python: CPython 3.9.12
                root: /code/SHeRLoc_pr/training
                startedAt: "2025-10-22T08:42:42.086627Z"
                writerId: vnnzrar536tbi9itx39a3hh4ds7q8tms
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
            "3":
                - 16
            "4": 3.9.12
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 200
dataset:
    value: hercules
dataset_folder:
    value: /code/SHeRLoc/src/dataset/HeRCULES
epochs:
    value: 20
loss:
    value: BatchHardTripletMarginLoss
lr:
    value: 0.001
margin:
    value: 1
model_params.model_params_path:
    value: ../models/Hetero_SHeRLoc.txt
model_params.radar_model:
    value: SHeRLoc
model_params.task:
    value: Hetero
model_params_path:
    value: ../models/Hetero_SHeRLoc.txt
num_workers:
    value: 1
params_path:
    value: ../config/config.txt
test_dataset:
    value: /code/SHeRLoc/src/dataset/HeRCULES
train_dataset:
    value: /code/SHeRLoc/src/dataset/HeRCULES
val_dataset:
    value: /code/SHeRLoc/src/dataset/HeRCULES
weight_decay:
    value: 0.001
