_wandb:
    value:
        cli_version: 0.21.0
        e:
            duixci7fp3oumyghbi74t2hz4w091dfq:
                args:
                    - --config
                    - ../config/config_radarloc.txt
                    - --model_config
                    - ../models/radarloc.txt
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982820896768"
                        used: "527452372992"
                email: hanjun815@snu.ac.kr
                executable: /usr/local/bin/python
                git:
                    remote: https://github.com/jac99/RadarLoc.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-613bca56-7650-58ea-cea6-94c3cc34e8a1
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-a31e0b07-58d8-9e0a-6719-71b064008565
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-9cdcf68d-1408-744c-07ff-057961003f3e
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-d48a224b-1aef-d6bb-78ac-56feeccc08f1
                host: oem-System-Product-Name
                memory:
                    total: "202280312832"
                os: Linux-6.8.0-40-generic-x86_64-with-glibc2.31
                program: /code/RLoc/training/train.py
                python: CPython 3.9.12
                root: /code/RLoc/training
                startedAt: "2025-09-01T05:25:46.585510Z"
                writerId: duixci7fp3oumyghbi74t2hz4w091dfq
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
            "3":
                - 16
            "4": 3.9.12
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
aug_mode:
    value: 2
batch_expansion_rate:
    value: 1.4
batch_expansion_th:
    value: 0.3
batch_size:
    value: 180
batch_size_limit:
    value: 256
dataset:
    value: mulran
dataset_folder:
    value: /code/SHeRLoc/src/dataset/HeRCULES
epochs:
    value: 20
loss:
    value: BatchHardTripletMarginLoss
lr:
    value: 0.001
margin:
    value: 1
model_params.lidar_model:
    value: null
model_params.model_params_path:
    value: ../models/radarloc.txt
model_params.output_dim:
    value: 256
model_params.radar_model:
    value: radarloc
model_params_path:
    value: ../models/radarloc.txt
num_workers:
    value: 1
params_path:
    value: ../config/config_radarloc.txt
scheduler_milestones:
    value:
        - 80
test_file:
    value: /code/SHeRLoc/src/dataset/HeRCULES/test_R_Day_384.pickle
train_file:
    value: /code/SHeRLoc/src/dataset/HeRCULES/train_R/Library_Day_Library_Night_5_50_polar_nav.pickle
val_file:
    value: /code/SHeRLoc/src/dataset/HeRCULES/val_R/Library_Day_Library_Night_5_50_polar_nav.pickle
weight_decay:
    value: 0.001
